name: CI Build
on:
  push:
    paths:
      - '*'

jobs:
  build-barcoder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get the latest commit hash
        run: echo "GIT_COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get the branch name
        run: echo "GIT_BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DOCKER_CR_ENDPOINT }}/${{ vars.DOCKER_IMAGE_NAME }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=edge
            type=sha
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_CR_ENDPOINT }}
          username: ${{ secrets.DOCKER_CR_USERNAME }}
          password: ${{ secrets.DOCKER_CR_PASSWORD }}


      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Barcoder/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}